# Generated by Django 5.2.13 on 2026-04-22 08:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penduduk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nik', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Nomor tidak valid (16 digit)', regex='^\\d{16}$')])),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('tempat_lahir', models.CharField(blank=True, max_length=80, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True, validators=[users.models.tanggal_lahir_validator])),
                ('jenis_kelamin', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Laki-laki'), (2, 'Perempuan')], null=True)),
                ('agama', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Islam'), (2, 'Kristen'), (3, 'Katolik'), (4, 'Hindu'), (5, 'Buddha'), (6, 'Konghucu'), (7, 'Kepercayaan terhadap Tuhan Yang Maha Esa')], null=True)),
                ('email', models.EmailField(max_length=160, unique=True)),
                ('no_hp', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='Nomor HP harus diawali 0 (bukan +62 atau 62) dan terdiri dari 10-15 digit angka', regex='^0\\d{9,14}$')])),
                ('status_kependudukan', models.PositiveSmallIntegerField(choices=[(1, 'Aktif'), (2, 'Pindah'), (3, 'Meninggal'), (4, 'Nonaktif')], default=1)),
                ('ktp_file', models.FileField(blank=True, null=True, upload_to=users.models.upload_ktp_final_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
            options={
                'db_table': 'penduduk',
            },
        ),
        migrations.CreateModel(
            name='JenisSurat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=120)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='template_surat/', validators=[users.models.JenisSurat.validate_template])),
            ],
            options={
                'db_table': 'jenis_surat',
            },
        ),
        migrations.CreateModel(
            name='KartuKeluarga',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nomor_kk', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Nomor tidak valid (16 digit)', regex='^\\d{16}$')])),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('kk_file', models.FileField(blank=True, null=True, upload_to=users.models.upload_kk_final_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
            options={
                'db_table': 'kartu_keluarga',
            },
        ),
        migrations.CreateModel(
            name='WilayahRT',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kode_rt', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'wilayah_rt',
            },
        ),
        migrations.CreateModel(
            name='WilayahRW',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kode_rw', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wilayah_rw',
            },
        ),
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penduduk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='akun', serialize=False, to='users.penduduk')),
                ('peran', models.PositiveSmallIntegerField(choices=[(1, 'Warga'), (2, 'RT'), (3, 'RW'), (4, 'Kepala Desa'), (5, 'Admin')])),
                ('terakhir_login_at', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('nip', models.CharField(blank=True, max_length=30, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'akun',
            },
        ),
        migrations.AddField(
            model_name='penduduk',
            name='kk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daftar_penduduk', to='users.kartukeluarga'),
        ),
        migrations.CreateModel(
            name='PermohonanSurat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomor_permohonan', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Diajukan'), (2, 'Ditolak'), (3, 'Selesai')])),
                ('data', models.JSONField(default=dict)),
                ('diajukan_at', models.DateTimeField(blank=True, null=True)),
                ('selesai_at', models.DateTimeField(blank=True, null=True)),
                ('jenis_surat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permohonan', to='users.jenissurat')),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permohonan_surat', to='users.penduduk')),
            ],
            options={
                'db_table': 'permohonan_surat',
            },
        ),
        migrations.CreateModel(
            name='DokumenSurat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('file_final', models.FileField(upload_to=users.models.upload_dokumen_surat_path)),
                ('dibuat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('permohonan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='users.permohonansurat')),
            ],
            options={
                'db_table': 'dokumen_surat',
            },
        ),
        migrations.CreateModel(
            name='BerkasPermohonan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_berkas', models.FileField(upload_to=users.models.upload_berkas_permohonan_path)),
                ('diunggah_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berkas', to='users.permohonansurat')),
            ],
            options={
                'db_table': 'berkas_permohonan',
            },
        ),
        migrations.AddField(
            model_name='penduduk',
            name='rt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penduduk', to='users.wilayahrt'),
        ),
        migrations.AddField(
            model_name='kartukeluarga',
            name='rt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daftar_kk', to='users.wilayahrt'),
        ),
        migrations.AddField(
            model_name='wilayahrt',
            name='rw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daftar_rt', to='users.wilayahrw'),
        ),
        migrations.CreateModel(
            name='RiwayatPersetujuan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tahap', models.PositiveSmallIntegerField(choices=[(1, 'RT'), (2, 'RW'), (3, 'ADMIN'), (4, 'Kepala Desa')])),
                ('aksi', models.PositiveSmallIntegerField(choices=[(1, 'Ajukan'), (2, 'Setuju'), (3, 'Tolak')])),
                ('catatan', models.TextField(blank=True, null=True)),
                ('waktu', models.DateTimeField(default=django.utils.timezone.now)),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='users.permohonansurat')),
                ('oleh_akun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aksi_riwayat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'riwayat_persetujuan',
            },
        ),
        migrations.CreateModel(
            name='PendaftaranAkun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomor_kk', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Nomor tidak valid (16 digit)', regex='^\\d{16}$')])),
                ('nik', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Nomor tidak valid (16 digit)', regex='^\\d{16}$')])),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField(validators=[users.models.tanggal_lahir_validator])),
                ('jenis_kelamin', models.PositiveSmallIntegerField(choices=[(1, 'Laki-laki'), (2, 'Perempuan')])),
                ('agama', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Islam'), (2, 'Kristen'), (3, 'Katolik'), (4, 'Hindu'), (5, 'Buddha'), (6, 'Konghucu'), (7, 'Kepercayaan terhadap Tuhan Yang Maha Esa')], null=True)),
                ('alamat', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=160, unique=True)),
                ('no_hp', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Nomor HP harus diawali 0 (bukan +62 atau 62) dan terdiri dari 10-15 digit angka', regex='^0\\d{9,14}$')])),
                ('password_hash', models.CharField(max_length=255)),
                ('kk_file', models.FileField(blank=True, null=True, upload_to=users.models.upload_kk_register_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('ktp_file', models.FileField(blank=True, null=True, upload_to=users.models.upload_ktp_register_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('status_verifikasi', models.PositiveSmallIntegerField(choices=[(1, 'Ditinjau'), (2, 'Ditolak'), (3, 'Disetujui')], default=1)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendaftaran_akun', to='users.wilayahrt')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendaftaran_diverifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pendaftaran_akun',
            },
        ),
        migrations.CreateModel(
            name='OTPEmail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tujuan', models.PositiveSmallIntegerField(choices=[(1, 'Login'), (2, 'Reset Password')])),
                ('kode_hash', models.CharField(max_length=255)),
                ('kedaluwarsa_at', models.DateTimeField()),
                ('dipakai_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_email',
            },
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipe', models.PositiveSmallIntegerField(choices=[(1, 'Pengajuan Baru'), (2, 'Verifikasi RT'), (3, 'Verifikasi RW'), (4, 'Verifikasi Admin'), (5, 'Verifikasi Kepala Desa'), (6, 'Ditolak'), (7, 'Selesai')])),
                ('sudah_dibaca', models.BooleanField(default=False)),
                ('dibaca_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('permohonan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to='users.permohonansurat')),
                ('penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifikasi',
            },
        ),
        migrations.AddConstraint(
            model_name='wilayahrt',
            constraint=models.UniqueConstraint(fields=('rw', 'kode_rt'), name='uniq_wilayah_rt_per_rw'),
        ),
        migrations.AddIndex(
            model_name='riwayatpersetujuan',
            index=models.Index(fields=['permohonan', '-waktu'], name='idx_riwayat_perm_waktu'),
        ),
        migrations.AddIndex(
            model_name='riwayatpersetujuan',
            index=models.Index(fields=['tahap', 'aksi'], name='idx_riwayat_tahap_aksi'),
        ),
        migrations.AddIndex(
            model_name='pendaftaranakun',
            index=models.Index(fields=['status_verifikasi'], name='idx_pendaftaran_status'),
        ),
        migrations.AddIndex(
            model_name='pendaftaranakun',
            index=models.Index(fields=['nik'], name='idx_pendaftaran_nik'),
        ),
        migrations.AddIndex(
            model_name='pendaftaranakun',
            index=models.Index(fields=['nomor_kk'], name='idx_pendaftaran_kk'),
        ),
        migrations.AddIndex(
            model_name='notifikasi',
            index=models.Index(fields=['penerima', 'sudah_dibaca', '-created_at'], name='idx_notif_user_baca_waktu'),
        ),
        migrations.AddIndex(
            model_name='notifikasi',
            index=models.Index(fields=['permohonan', '-created_at'], name='idx_notif_perm_waktu'),
        ),
        migrations.AddIndex(
            model_name='notifikasi',
            index=models.Index(fields=['tipe'], name='idx_notif_tipe'),
        ),
    ]
